### ISSUE TITLE
remove_unresponsive.py triggers DOS protection on some hosting providers

### ISSUE THREAD

**Issue by xopr** [SpaceApi/directory#49]
In some cases, a denial of service protection is triggered when using the `remove_unresponsive.py` is used.

Currently, it is not clear if this happens due to repetitive scanning, arbitrary user-agent sting or scanning invalid (sub-)urls.

The result is that the hosting provider denies all traffic which looks like an offline server to the scan tool.

See [my comment on a commit](https://github.com/fixme-lausanne/OpenSpaceDirectory/commit/ac28dd53223b048374fd8368510699f2f092e2a3#commitcomment-23630552)

**Comment by rorist** [comment]
Hello,

The script was run manually from my machine with a public ip address from my university, I probably ran the script twice IIRC.

I can add some better user agent for a start.

**Comment by stuiterveer** [comment]
Is this script always run from the same IP or does it depend on the location you're in at that time? Wouldn't it be better to fire it from the same server and IP every time at regular intervals? If hosting is an issue I'm also willing to help if needed and I'm sure others would be as well.

**Comment by rorist** [comment]
The script is not reliable enough that we can run it automatically I would say. That's why I'm running it manually from time to time and it's also ran from Travis with a new commit.

I usually check each endpoint before removing them, but yours got removed by mistake. We should probably redo this so it's more consistent so we it can be done automatically. Thing is, some endpoint sometimes are unavailable temporarily.

**Comment by rorist** [comment]
> is it safe to assume that the IP block comes from the University of Lausanne

I would say no, we can establish that I'll run the tests from the FIXME network every time: `62.220.135.192/26`

**Comment by gidsi** [comment]
fixed by #139
