### ISSUE TITLE
Move this repository back to the SpaceApi organization?

### ISSUE THREAD

**Issue by rnestler** [SpaceApi/directory#87]
Many thanks to you guys to take care of the space directory while the SpaceAPI project was inactive!

Since then we reactivated the project and would like to keep it alive with a core team consisting of multiple people from multiple hackerspace (https://github.com/orgs/SpaceApi/teams/core).

Would it make sense to move the repository back to the SpaceAPI organization and keep it up to date there? Also would one of you guys want to participate in the SpaceAPI core team?

cc @dbrgn @gidsi

**Comment by rorist** [comment]
Hi there, 

Sure !!! Sorry for the long delay :)

So you want to rename the repository spaceapi-archive ? and start a new one for the directory ? Will it still be PR based ?

Cheers

**Comment by dbrgn** [comment]
I see two possibilities:

- Merge all changes into https://github.com/SpaceApi-archive/OpenSpaceDirectory and then move that to the `SpaceApi` organization (so it wouldn't have `archive` in the name anymore). This will result in redirects from SpaceApi-archive/OpenSpaceDirectory to SpaceApi/OpenSpaceDirectory
- Move this repository to SpaceApi/OpenSpaceDirectory and unlink it from the parent repository. This will result in redirects from fixme-lausanne/OpenSpaceDirectory to SpaceApi/OpenSpaceDirectory

The second option would be my favorite, because there are now a few links pointing to the fixme-lausanne repo for submitting changes, and this way we get an automatic redirect by GitHub. The parent repository (SpaceApi-archive/OpenSpaceDirectory) can be unlinked.

Opinions, @rnestler @gidsi?

**Comment by rorist** [comment]
+1 for the second option and the free redirection ! Why unlink it from the parent, is there a practical reason ?

**Comment by dbrgn** [comment]
No, but it shouldn't be a fork if it's the authoritative repository :slightly_smiling_face:

**Comment by gidsi** [comment]
Both have their pros and cons, I would be fine with either.

**Comment by rnestler** [comment]
>     Move this repository to SpaceApi/OpenSpaceDirectory and unlink it from the parent repository. This will result in redirects from fixme-lausanne/OpenSpaceDirectory to SpaceApi/OpenSpaceDirectory

I'm also in favor of that one :slightly_smiling_face:

**Comment by dbrgn** [comment]
@rorist Ok, could you move the repository to the https://github.com/SpaceApi organization? Once that's done we can start updating the links to it.

**Comment by rorist** [comment]
Great, I need the permission to create repositories on the organization to be able to do the transfer.

**Comment by dbrgn** [comment]
@rorist you don't actually need permission to create the repo, you can simply transmit ownership :)

Thanks for the admin rights, I'll transfer it.

**Comment by rorist** [comment]
I did the Transfer and got an error saying I need create permission ;)

**Comment by dbrgn** [comment]
Repo is transferred and renamed! :tada: 

For some reason I can't unlink it. Maybe that only worked on GitLab? The docs say that we can contact support to do it though. I'll do that.

@rorist I invited you as collaborator with adminrights on this repo!

**Comment by dbrgn** [comment]
> The docs say that we can contact support to do it though. I'll do that.

Done

**Comment by dbrgn** [comment]
Fork was unlinked from the parent by GitHub staff!
